#!/usr/bin/python3
import sys
import requests as r
import argparse


class bcolors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    END = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'


ap = argparse.ArgumentParser()
ap.add_argument("-m", "--method", required=True,
                help="method to be used: get or add")
ap.add_argument("-t", "--title", required=False,
                help="title for the page [optional]")
ap.add_argument("-u", "--url", required=False,
                help="url of the page")
args = vars(ap.parse_args())

method = args["method"]
url = args["url"]
inTitle = args["title"]

if (method == "get"):
    res = r.get("http://clipboard-api.herokuapp.com/public/" + str(url))
    sCode = res.status_code
    res = res.json()['results']
    if sCode == 200 and res['Success']:
        outTitle = res['pageTitle']
        body = res['pageBody']
        print(bcolors.BOLD + bcolors.BLUE + "Title: " + bcolors.END,
              bcolors.GREEN + outTitle + bcolors.END)
        print()
        print(bcolors.BOLD + bcolors.BLUE + "Body: " + bcolors.END,
              bcolors.GREEN + body + bcolors.END)
    else:
        comment = res["Comment"]
        print(bcolors.BOLD + bcolors.FAIL +
              "Umm this is embarassing but there is an error." + bcolors.END)
        print(bcolors.BOLD + bcolors.BLUE + "Reason: " + bcolors.END,
              bcolors.GREEN + comment + bcolors.END)

elif(method == "add"):
    print(bcolors.BOLD + "Enter Body text:" + bcolors.END)
    body = input().strip()
    res = r.post("http://clipboard-api.herokuapp.com/public/" +
                 str(url), json={'pageBody': body, 'pageTitle': inTitle})
    sCode = res.status_code
    res = res.json()['results']
    if sCode == 200 and res['Success']:
        outTitle = res['pageTitle']
        body = res['pageBody']
        print(bcolors.BOLD + bcolors.WARNING +
              "Done!" + bcolors.END)
        print(bcolors.BOLD + bcolors.BLUE + "Title: " + bcolors.END,
              bcolors.GREEN + outTitle + bcolors.END)
        print()
        print(bcolors.BOLD + bcolors.BLUE + "Body: " + bcolors.END,
              bcolors.GREEN + body + bcolors.END)
    else:
        comment = res["Comment"]
        print(bcolors.BOLD + bcolors.FAIL +
              "Umm this is embarassing but there is an error." + bcolors.END)
        print(bcolors.BOLD + bcolors.BLUE + "Reason: " + bcolors.END,
              bcolors.GREEN + comment + bcolors.END)

else:
    print(bcolors.BOLD + bcolors.FAIL +
          "Sorry bro.. that's not a method. Try clipboard --help" + bcolors.END)
